version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    networks:
      - nginx-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
networks:
  nginx-network:
    driver: bridge